# Generated by Django 4.2.25 on 2025-10-10 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='evento',
            name='cupos',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='deporte',
            field=models.CharField(choices=[('futbol', 'Fútbol'), ('baloncesto', 'Baloncesto'), ('voleibol', 'Voleibol'), ('tenis', 'Tenis'), ('natacion', 'Natación'), ('atletismo', 'Atletismo')], default='futbol', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='nivel',
            field=models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
