# Generated by Django 4.2.25 on 2025-10-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_creado_en_evento_cupos_evento_deporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
